### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by MoKaif** [MoKaif/Stroke_Prediction_System#1]

**Comment by Ramghosh16RG** [comment]
#1 Hi @MoKaif,

I wanted to let you know that the requested updates for the Stroke Prediction System have been completed. I've thoroughly tested the changes and believe they enhance the overall user experience.

If you have any final feedback or if there are additional steps needed, please let me know. Otherwise, I propose closing this issue.

Thanks for your time and consideration.

Best regards,
My Team.

**Comment by MoKaif** [comment]
Thank you, @Ramghosh16RG , for your hard work in completing this task! Your efforts are greatly appreciated. 👏

I'm pleased to confirm that the issue has been successfully resolved. As such, I'm closing this issue now. If you have any further questions or need assistance with anything else, please don't hesitate to reach out.

Thanks again for your dedication and contribution to our project! 🙌
